eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: service-feign
feign:
  hystrix:
    enabled: true
ribbon:
  eureka:
    enabled: true
  ReadTimeout: 120000 #处理超时时间 默认5秒
  ConnectTimeout: 120000 #连接超时时间 默认2秒
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 120000 #断路切换超时