#========================================server config=====================================
server:
  port: 9100
#========================================spring config=====================================
spring:
  application:
    name: seata-springcloud-account
  devtools:
    restart:
      enabled: false
#========================================MySQL config=====================================
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/car?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
      username: root
      password: root

#========================================mybatis config=====================================
mybatis:
  type-aliases-package: com.sly.seata.common.model
  mapper-locations: classpath:mapper/*.xml
#========================================eureka config=====================================
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/

