#========================================server config=====================================
server:
  port: 7000
#========================================spring config=====================================
spring:
  application:
    name: seata-springcloud-eureka
  devtools:
    restart:
      enabled: false
#========================================eureka config=====================================
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
